def protein_mass(seq: str) -> float:
    m = 0
    for aa in seq:
        m += aa_mass[aa]
    return m


mass_filename = 'isotropic_aa_mass.txt'
protein_sample = 'HHYQSWSDKCDCGWFSIEWYPVWCRMGEWYAPNDYLINPCLGVSCCVNMQFQQLTPKYATEMRHPGQPYVKAVNECRWYDYKEMPDQNRGEDKCCYESGECMCVEHMFTQSFIAHFVWKTSTCDEQWHQDCFAWYPFRTFPKSTLQGYVEHPTTFSWPAAGVMFGKNWQKLHDTLTRVMKICTPLEYLDIDMEHNGRRERAMLLSEMGNPQCFQCIDDKSLAPDIQVWIVLPKMCPWAYSQVQKEIIQGSAIKQSQVGRHISRGNENTIMRWEPFMLIMDVKWPVYIGIQLRTCYWHYDFRLEWQEQNMSGKINPDHFNIAIAWDFKAECPAQFCFVISLRRHFYMTMPMDMDHQLPNSKPHHRAQQPWGIGYQPNMSTICVDKKSILPDHCLWCPRVRIQECCRWILQSAAGVPDCKGRANTAQECEEWTNEQCCWNCTCETTGPVFTMHNPCVKCTNHFNWIVLGINKPSVAKHHPGCMGVRAGDIKTFWPWDYAGAIQSKVDQGSKMQNKWQLNYQIKCIMPLIKHDRHIQRPTYPEEAGYHIATVNTSPPTQTQQPAACMFVATMHGNMMGWEMFDDCDYMGCPKSQWITEWYISGCRMAYIAYIEAERDDLVRHMKCCVKWNKLRHQICFKRSIMKMAADVVRFWAHIYGSQLHNIADQRNIILQSEGCTESDKPIYKHGTAFRKIEMDYFGHAMPHVCWCWLPCDNQYMSWYCHNAGDYMPYVGPLEQVWNCRMNGSHATQKVHGNNINGVTYCPEKTYNQKSGEGYEAQWWERAAMRGHFMPHSHKYNVNRWTTQLESYEMALVWTYKVKPRNDGEPANSTEKFDKWYGHDDDQMYID'

if __name__ == '__main__':

    # Preparing mass dict
    with open(mass_filename, 'r') as file:
        lines = [line.strip().replace('  ', ' ') for line in file.readlines()]
    aa_mass = {}
    for aa, m in [(line.split()) for line in lines]:
        aa_mass[aa] = float(m)
    print(aa_mass)

    print(protein_mass(protein_sample))

