
def locate_motif(string: str, motif: str) -> list:
    assert len(string) >= len(motif)
    motif_locations = []
    for i in range(len(string) - len(motif) + 1):
        if string[i:i + len(motif)] == motif:
            motif_locations.append(i + 1)  # String position is 1-indexed
    return motif_locations


s = 'TGCTATTAAATCTATTAACTATTAAGCTATTAACGCTATTAACTATTAAACTATTAAAGTCTATTAACAACACTATTAACTATTAAGGCTATTAACCCTATTAACTATTAAAGGTTCTATTAACTATTAACTATTAACTAACTATTAACGCTATTAAGCTATTAAGTCTATTAACGTACGCACTATTAAAGTTCTATTAACTATTAAACTATTAAACACCAGCTATTAAGTCTTTACTATTAATACACTATTAAACTATTAACGAATTAGGTCTATTAAAACTATTAATGCTATTAACCTATTAACTCAGTGCCTATTAACTATTAAATTCTATTAATGTCTATTAACACTATTAACTATTAACTATTAACTATTAATTATCGCTATTAATCACTATTAAATAGCCGACTATTAACTATTAAAGCTATTAAACCTATTAATCTATTAACTCGTTCTATTAATCGATCTATTAATCTATTAACCTATTAACTATTAACCTATTAAGTCCTATTAACACCCTATTAAACTGGCGATTCGCTATTAAACTATTAATGTCTATTAAGGACTATTAATTCTATTAACTATTAACCTATTAAGTATTGATCTATTAACGACACACGCTATTAACTATTAACAAGCTATTAACTATTAAACTATTAACTATTAACTATTAACATACACCTATTAAGTCTCTCCCTATTAATTACTATTAATAACGGCTATTAACTATTAACCTATTAACTATTAACCTCAAAGCTATTAACTATTAACCTATTAAACTATTAACACCCTCTATTAAAACTATTAACTATTAAAACTATTAATCTATTAACGCGCGCTAGCTATTAATCTATTAAGGCACGGCTATTAAGCTATTAACTATTAACTATTAACTATTAATGCCCTATTAATCTATTAATCTATTAAGATCTCAACTATTAAGATGCCATCTATTAACTTCTATTAAC'
t = 'CTATTAACT'

if __name__ == '__main__':
    print(*locate_motif(s, t))