def count_nucleotide(nucleotide: str, sequence: str):
    count = 0
    for p in range(len(sequence)):
        if sequence[p] == nucleotide:
            count += 1
    return count


nucleotides = ['A', 'C', 'G', 'T']
dna_sample = 'TGTTTGGTATGATTAAAACGATACGACTTCATGGCTCCATCGTGCGCGGCTATTTGTTGCGCTCAATATGCCGCTCGTATCATGCAGGTCGTGGCGAGATAGGGTAGCAAAAATGTTCGACAGACAACTTAAAAAGACTCAAACAGGGTGTTACTGTACGTGAAGTAACTGGCTCATATAGGGAACACCGACAATACACTTAGAGCCGGTCAATTGAGGTGAATGCGAGCTGGCCCTGCAGAGGAGTCCAGTTTCGAGTCCAACTGTCATCCCTAATCTTAAGCGTAGCTTACTGGGTGGTTGGCAACCTCGTCAGGTGCTATGCTCCTATGACAAACACATTGTTTAGATCCTGCGCGCCACGTATGCATGCTCGCAGATTCCGTATGGGCCGAGTCTTGAGCCGTAGGCTGTATTTGGAAGCTTGAGCGCAGAGTCCTTTGCGCTTGTATGAAGAGAGTACTAATTGCATTACCGGAGCATTGTGATAGAGGCACAAACGGGAGGATGCTTAGATCGTTAGGATCATGGACATCCAGGGGAAGTATGGTTCGTCAGCGACTGACATAGGATTACATATACCCTTCATGAGCACTGGCACATATATCCTGGAAGCGCATACAGAGATACCATTTGCCCTACGTGTTGGAAGGGCGCCCCGAATTGACGTATGAGGTCAGGCGTGGGTCATGGTGGCAGCGCTCTACACATTTGGGAATATGAGGTGCCTGAAGAAAAAAACCTACGTGGCATGATCGCTACATTCCAAGGGGTCGCGCTGGAATCTAGTACCACTTAGGAATTGGCGAGCTGGCTTTCGTCGCCACAGGTAGACGTTATCAATCGCGCCAGCGTTGTAGTATGCTAAGTAGCTGGGGACATCGGGGAGCCTGCGAAATGTCCCCTCATTTATGTTTGAGGGGGGTGCGCATCCCTCGAGCTACTCGATATCCCTGATCTGGACGCCTCTTAACATTCTTGTTTTCCTATAACGTGAGT'


if __name__=='__main__':
    counts = {}
    for n in nucleotides:
        counts[n] = count_nucleotide(n, dna_sample)
    print(*counts.values(), sep=" ")
